name: Audit Log on Push

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log commit SHA
        run: echo "📦 Repo updated with commit ${{ github.sha }}"
