name: Deploy to Firebase Hosting and Functions

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions dependencies
        run: npm install
        working-directory: functions

      - name: Deploy Functions
        run: firebase deploy --only functions --project swingtraderdash-1a958
        working-directory: functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}

      - name: Deploy Hosting
        run: firebase deploy --only hosting --project swingtraderdash-1a958
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

